[icons]
# Material Design Icons
# Web
Firefox = "󰈹"
# Terminal
Alacritty = "󰞷"
# Games
retroarch = "󰊖"
dolphin = "󰮭"
slippi = "󰮭"
nethack = "󰒘"
brogue = "󰞇"
minecraft = "󰍳"
Gucharmap = "󰏉"
Steam = "󰓓"
cataclysm = "󱡞"
sil-q = "󰓥"
# General
# Coding
Thunderbird = "󰇮"
Spotify = "󰓇"
keepassxc = "󱦃"
libreoffice-startcenter = "󰈙"
Soffice = "󰈙"
libreoffice-writer = "󰷈"
libreoffice-math = "󰃬"
libreoffice-calc = "󰪚"
lightcord = "󰙯"
VSCodium = "󰅱"
gimp = "󰉼"
java = "󰬷"
wine = "󰡶"
wineskin = "󰊨"
winebottler = "󰊧"
protonmail-bridge = "󰒃"

[options]
no_icon_names = true

[general]
default_icon = "󰽥"
