[icons]
# Material Design Icons
# Web
firefox = "󰈹"
# Terminal
Alacritty = "󰞷"
XTerm = "󰞷"
kitty = "󰄛"
# Games
retroarch = "󰊖"
dolphin = "󰮭"
slippi = "󰮭"
"Slippi Launcher" = "󰮭" 
nethack = "󰒘"
brogue = "󰞇"
minecraft = "󰍳"
Gucharmap = "󰏉"
Steam = "󰓓"
cataclysm = "󰐼"
sil-q = "󰓥"
Pcsx2 = "󰊗"
Lutris = "󰮃"
# General
Thunderbird = "󰇮"
Spotify = "󰓇"
KeePassXC = "󰀋"
libreoffice-startcenter = "󰈙"
Soffice = "󰈙"
libreoffice-writer = "󰷈"
libreoffice-math = "󰃬"
libreoffice-calc = "󰪚"
discord = "󰙯"
VSCodium = "󰅱"
Thunar = "󱉥"
gimp = "󰉼"
java = "󰬷"
python = "󰌠"
wine = "󰡶"
wineskin = "󰊨"
winebottler = "󰊧"
"Proton Mail Bridge" = "󰒃"
vim = "󰗧"
neovim = "󰗧"
fontforge = "󰬴"
vlc = "󰕼"
obs = "󰦳"
Tenacity = "󰽰"

[options]
no_icon_names = true

[general]
default_icon = "󰽥"
