[icons]
# Material Design Icons
# Web
firefox = "󰈹"
# Terminal
Alacritty = "󰞷"
XTerm = "󰞷"
UXTerm = "󰞷"
kitty = "󰄛"
# Games
retroarch = "󰊖"
nethack = "󰒘"
brogue = "󰞇"
minecraft = "󰍳"
steam = "󰓓"
cataclysm = "󰐼"
sil-q = "󰓥"
Pcsx2 = "󰊗"
Mednaffe = "󰊗"
Lutris = "󰮃"
# General
Thunderbird = "󰇮"
KeePassXC = "󰀋"
libreoffice-startcenter = "󰈙"
Soffice = "󰈙"
libreoffice-writer = "󰷈"
libreoffice-math = "󰃬"
libreoffice-calc = "󰪚"
VSCodium = "󰅱"
Thunar = "󱉥"
Gimp = "󰸌"
java = "󰬷"
python = "󰌠"
wine = "󰡶"
wineskin = "󰊨"
winebottler = "󰊧"
vim = "󰗧"
neovim = "󰗧"
vlc = "󰕼"
obs = "󰦳"
Gucharmap = "󰏉"
dosbox = "󰨣"
Arandr = "󱜤"
sioyek = "󰈦"

[options]
no_icon_names = true

# [general]
# default_icon = "󰽥"
