[icons]
# Material Design Icons
# Web
firefox = "󰈹"
# Terminal
Alacritty = "󰞷"
# Games
retroarch = "󰊖"
dolphin = "󰮭"
slippi = "󰮭"
nethack = "󰒘"
brogue = "󰞇"
minecraft = "󰍳"
Gucharmap = "󰏉"
Steam = "󰓓"
cataclysm = "󰐼"
sil-q = "󰓥"
# General
Thunderbird = "󰇮"
Spotify = "󰓇"
keepassxc = "󰀋"
libreoffice-startcenter = "󰈙"
Soffice = "󰈙"
libreoffice-writer = "󰷈"
libreoffice-math = "󰃬"
libreoffice-calc = "󰪚"
discord = "󰙯"
VSCodium = "󰅱"
thunar = "󱉥"
gimp = "󰉼"
java = "󰬷"
python = "󰌠"
wine = "󰡶"
wineskin = "󰊨"
winebottler = "󰊧"
protonmail-bridge = "󰒃"
vim = "󰗧"
neovim = "󰗧"
fontforge = "󰬴"
vlc = "󰕼"

[options]
no_icon_names = true

[general]
default_icon = "󰽥"
